Updated xps_library for 2021

diff --git a/startsg b/startsg
--- a/startsg
+++ b/startsg
@@ -81,6 +81,16 @@ then
   $on_error 1
 fi
 
+if ! [ -n "${COMPOSER_PATH}" ]
+then
+  echo "ERROR: COMPOSER_PATH is not defined in the current environment."
+  $on_error 1
+elif ! [ -d "${COMPOSER_PATH}" -a -r "${COMPOSER_PATH}" ]
+then
+  echo "ERROR: COMPOSER_PATH '${COMPOSER_PATH}' is not a readable directory."
+  $on_error 1
+fi
+
 if ! [ -n "${XILINX_PATH}" ]
 then
   echo "ERROR: XILINX_PATH is not defined in the current environment."
@@ -151,6 +161,7 @@ fi
 
 # Make sure that these variables are exported
 export XILINX_PATH
+export COMPOSER_PATH
 export MATLAB_PATH
 export PLATFORM
 export MLIB_DEVEL_PATH
@@ -160,6 +171,7 @@ export HDL_DSP_DEVEL_PATH
 # Show environment essentials
 echo "Using MATLAB_PATH=${MATLAB_PATH}"
 echo "Using XILINX_PATH=${XILINX_PATH}"
+echo "Using COMPOSER_PATH=${COMPOSER_PATH}"
 echo "Using PLATFORM=${PLATFORM}"
 echo "Using MLIB_DEVEL_PATH=${MLIB_DEVEL_PATH}"
 echo "Using JASPER_BACKEND=${JASPER_BACKEND}"
@@ -175,11 +187,11 @@ export MATLAB="$MATLAB_PATH"
 export CASPER_BASE_PATH="$MLIB_DEVEL_PATH"
 export HDL_ROOT="$CASPER_BASE_PATH/jasper_library/hdl_sources"
 
-if [ -f "${XILINX_PATH}/settings64.sh" ]
+if [ -f "${COMPOSER_PATH}/settings64.sh" ]
 then
-  source "${XILINX_PATH}/settings64.sh" > /dev/null
+  source "${COMPOSER_PATH}/settings64.sh" > /dev/null
 else
-  echo "ERROR: Xilink settings script '${XILINX_PATH}/settings64.sh' not found."
+  echo "ERROR: Xilink settings script '${COMPOSER_PATH}/settings64.sh' not found."
   $on_error 1
 fi
 
@@ -195,11 +207,14 @@ then
   # Save start-up directory (if defined, startup.m will cd there)
   export CASPER_STARTUP_DIR=`pwd`
 
+
+  echo "Changing to directory: ${MLIB_DEVEL_PATH}"
   # Change into the MLIB_DEVEL_PATH directory
   # (so MATLAB will find our startup.m file).
   cd "${MLIB_DEVEL_PATH}"
 
   # Start sysgen in OPENGL graphics mode to prevent java errors
-  "${XILINX_PATH}/bin/sysgen" -softwareopengl
-
+  echo "Starting model_composer"
+  #"${COMPOSER_PATH}/bin/model_composer" 
+  model_composer
 fi
